# HTTP
quarkus.http.port=8080

# OIDC Configuration
quarkus.oidc.auth-server-url=https://localhost:8180/realms/keycloakcon
quarkus.oidc.client-id=keycloakcon-webapp
quarkus.oidc.application-type=web-app
quarkus.oidc.credentials.jwt.token-path=/tmp/svid.json
quarkus.oidc.credentials.jwt.source=bearer
quarkus.oidc.credentials.jwt.issuer=https://spire-spiffe-oidc-discovery-provider.apps.mycluster.local
quarkus.oidc.credentials.jwt.subject=spiffe://apps.mycluster.local/ns/keycloakcon/sa/keycloakcon-webapp
quarkus.oidc.authentication.redirect-path=/
quarkus.oidc.authentication.restore-path-after-redirect=true
